# Generated by Django 3.2.14 on 2022-09-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generation_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.TextField(verbose_name='station_type')),
                ('genertion', models.FloatField(verbose_name='generation')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'Генерация по источникам',
                'verbose_name_plural': 'Генерация по источникам',
            },
        ),
    ]
