# Generated by Django 3.2.14 on 2022-07-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_RSV', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices_rsv_from_ats',
            options={'verbose_name': 'Цена РСВ с сайта АТС', 'verbose_name_plural': 'Цена РСВ с сайта АТС'},
        ),
    ]
