# Generated by Django 3.2.14 on 2022-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_RSV', '0002_alter_prices_rsv_from_ats_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.TextField(verbose_name='Станция')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('gen_company', models.TextField(verbose_name='Станция')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Цены РСВ для всех компаний',
                'verbose_name_plural': 'Цены РСВ для всех компаний',
            },
        ),
    ]
